services:
  db:
    image: postgres:16-alpine
    environment:
      CLIENT_URL: ${CLIENT_URL:-https://109.120.152.26}
      POSTGRES_DB: ${POSTGRES_DB:-timp4lab}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pg_data_prod:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      NODE_ENV: production
      PORT: 3001
      CLIENT_URL: ${CLIENT_URL:-http://109.120.152.26}
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      CLAIM_ADMIN_SECRET: ${CLAIM_ADMIN_SECRET}
      REFRESH_COOKIE_NAME: refreshToken
      ACCESS_TOKEN_TTL: 15m
      REFRESH_TOKEN_TTL: 7d
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pg_data_prod:
